config/routes.rb
Owpns::Application.routes.draw do
  resources :posts

  resources :devices

end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :system, :token
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @devices }
    end
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
    @device = Device.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/new
  # GET /devices/new.json
  def new
    @device = Device.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @device }
    end
  end

  # GET /devices/1/edit
  def edit
    @device = Device.find(params[:id])
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.find(:token => params[:device])
    
    @device = Device.new(params[:device]) if @device.nil?

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render json: @device, status: :created, location: @device }
      else
        format.html { render action: "new" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /devices/1
  # PUT /devices/1.json
  def update
    @device = Device.find(params[:id])

    respond_to do |format|
      if @device.update_attributes(params[:device])
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device = Device.find(params[:id])
    @device.destroy

    respond_to do |format|
      format.html { redirect_to devices_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
require 'apns'
require 'gcm'

class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])
    
    android_registration_ids = []
  	ios_registration_ids = []
  	
  	# Collect all devices' tokens
  	Device.all.each do |device|
  		if device.system == "android"
  			android_registration_ids << device.token
  		else # iOS
    		ios_registration_ids << device.token
  		end
		end
		
		# Android Notification
		
		gcm = GCM.new("AIzaSyD6toaexYzMySpzuIdyKZSnnb65ESgNiJ4")
		options = {data: {message: @post.body}, collapse_key: "updated_message"}
		gcm.send_notification(android_registration_ids, options)
    
    # iOS Notification
    
		APNS.pem = Rails.root.join("files", "cert.pem")
		APNS.host = 'gateway.push.apple.com'
    APNS.feedback_host = 'feedback.push.apple.com'
    
    # APNS.feedback.each do |feedback|
    #   d = Device.find(:first, :conditions => { :token = feedback.device_token })
    #   unless d.nil?
    #     d.feedback_on = feedback.feedback_on
    #   end
    # end
    
    APNS.pass = ''
		notifications = []
		ios_registration_ids.each do |token|
		  notifications << [token, :aps => { :alert => @post.body, :sound => 'default' }]
		end
		APNS.send_notifications(notifications)
		
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :token %><br />
    <%= f.text_field :token %>
  </div>
  <div class="field">
    <%= f.label :system %><br />
    <%= f.text_field :system %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<h1>Listing devices</h1>

<table>
  <tr>
    <th>Token</th>
    <th>System</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @devices.each do |device| %>
  <tr>
    <td><%= device.token %></td>
    <td><%= device.system %></td>
    <td><%= link_to 'Show', device %></td>
    <td><%= link_to 'Edit', edit_device_path(device) %></td>
    <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Token:</b>
  <%= @device.token %>
</p>

<p>
  <b>System:</b>
  <%= @device.system %>
</p>


<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Owpns</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.body %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Body:</b>
  <%= @post.body %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>